// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/BankAccount.proto

package com.iquantex.phoenix.samples.account.api.protobuf;

public final class Account {
    private Account() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface AccountCreateCmdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountCreateCmd)
                                              com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        boolean hasAccountCode();

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        String getAccountCode();

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        com.google.protobuf.ByteString getAccountCodeBytes();

        /**
         * <pre>
         * 账户余额
         * </pre>
         *
         * <code>optional double balanceAmt = 2;</code>
         */
        boolean hasBalanceAmt();

        /**
         * <pre>
         * 账户余额
         * </pre>
         *
         * <code>optional double balanceAmt = 2;</code>
         */
        double getBalanceAmt();
    }

    /**
     * Protobuf type {@code AccountCreateCmd}
     */
    public static final class AccountCreateCmd extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AccountCreateCmd)
                                                                                             AccountCreateCmdOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use AccountCreateCmd.newBuilder() to construct.
        private AccountCreateCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private AccountCreateCmd() {
            accountCode_ = "";
            balanceAmt_ = 0D;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private AccountCreateCmd(com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                             throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            accountCode_ = bs;
                            break;
                        }
                        case 17: {
                            bitField0_ |= 0x00000002;
                            balanceAmt_ = input.readDouble();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return Account.internal_static_AccountCreateCmd_descriptor;
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return Account.internal_static_AccountCreateCmd_fieldAccessorTable.ensureFieldAccessorsInitialized(
                AccountCreateCmd.class, Builder.class);
        }

        private int                       bitField0_;
        public static final int           ACCOUNTCODE_FIELD_NUMBER = 1;
        private volatile Object accountCode_;

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        public boolean hasAccountCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        public String getAccountCode() {
            Object ref = accountCode_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    accountCode_ = s;
                }
                return s;
            }
        }

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        public com.google.protobuf.ByteString getAccountCodeBytes() {
            Object ref = accountCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                accountCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BALANCEAMT_FIELD_NUMBER = 2;
        private double          balanceAmt_;

        /**
         * <pre>
         * 账户余额
         * </pre>
         *
         * <code>optional double balanceAmt = 2;</code>
         */
        public boolean hasBalanceAmt() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 账户余额
         * </pre>
         *
         * <code>optional double balanceAmt = 2;</code>
         */
        public double getBalanceAmt() {
            return balanceAmt_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeDouble(2, balanceAmt_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(2, balanceAmt_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof AccountCreateCmd)) {
                return super.equals(obj);
            }
            AccountCreateCmd other = (AccountCreateCmd) obj;

            boolean result = true;
            result = result && (hasAccountCode() == other.hasAccountCode());
            if (hasAccountCode()) {
                result = result && getAccountCode().equals(other.getAccountCode());
            }
            result = result && (hasBalanceAmt() == other.hasBalanceAmt());
            if (hasBalanceAmt()) {
                result = result
                         && (Double.doubleToLongBits(getBalanceAmt()) == Double
                             .doubleToLongBits(other.getBalanceAmt()));
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasAccountCode()) {
                hash = (37 * hash) + ACCOUNTCODE_FIELD_NUMBER;
                hash = (53 * hash) + getAccountCode().hashCode();
            }
            if (hasBalanceAmt()) {
                hash = (37 * hash) + BALANCEAMT_FIELD_NUMBER;
                hash = (53 * hash)
                       + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getBalanceAmt()));
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static AccountCreateCmd parseFrom(java.nio.ByteBuffer data)
                                                                                  throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AccountCreateCmd parseFrom(java.nio.ByteBuffer data,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                     throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AccountCreateCmd parseFrom(com.google.protobuf.ByteString data)
                                                                                             throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AccountCreateCmd parseFrom(com.google.protobuf.ByteString data,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                     throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AccountCreateCmd parseFrom(byte[] data)
                                                                     throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AccountCreateCmd parseFrom(byte[] data,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                     throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AccountCreateCmd parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static AccountCreateCmd parseFrom(java.io.InputStream input,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                     throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static AccountCreateCmd parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static AccountCreateCmd parseDelimitedFrom(java.io.InputStream input,
                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                              throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static AccountCreateCmd parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                    throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static AccountCreateCmd parseFrom(com.google.protobuf.CodedInputStream input,
                                                         com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                     throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(AccountCreateCmd prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code AccountCreateCmd}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
                                                                                                         implements
                                                                                                         // @@protoc_insertion_point(builder_implements:AccountCreateCmd)
                                                                                                         AccountCreateCmdOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return Account.internal_static_AccountCreateCmd_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return Account.internal_static_AccountCreateCmd_fieldAccessorTable.ensureFieldAccessorsInitialized(
                    AccountCreateCmd.class, Builder.class);
            }

            // Construct using com.iquantex.phoenix.bankaccount.api.protobuf.Account.AccountCreateCmd.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                accountCode_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                balanceAmt_ = 0D;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return Account.internal_static_AccountCreateCmd_descriptor;
            }

            public AccountCreateCmd getDefaultInstanceForType() {
                return AccountCreateCmd.getDefaultInstance();
            }

            public AccountCreateCmd build() {
                AccountCreateCmd result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public AccountCreateCmd buildPartial() {
                AccountCreateCmd result = new AccountCreateCmd(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.accountCode_ = accountCode_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.balanceAmt_ = balanceAmt_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                            Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof AccountCreateCmd) {
                    return mergeFrom((AccountCreateCmd) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(AccountCreateCmd other) {
                if (other == AccountCreateCmd.getDefaultInstance())
                    return this;
                if (other.hasAccountCode()) {
                    bitField0_ |= 0x00000001;
                    accountCode_ = other.accountCode_;
                    onChanged();
                }
                if (other.hasBalanceAmt()) {
                    setBalanceAmt(other.getBalanceAmt());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                 throws java.io.IOException {
                AccountCreateCmd parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (AccountCreateCmd) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int              bitField0_;

            private Object accountCode_ = "";

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public boolean hasAccountCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public String getAccountCode() {
                Object ref = accountCode_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        accountCode_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public com.google.protobuf.ByteString getAccountCodeBytes() {
                Object ref = accountCode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((String) ref);
                    accountCode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public Builder setAccountCode(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                accountCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public Builder clearAccountCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                accountCode_ = getDefaultInstance().getAccountCode();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public Builder setAccountCodeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                accountCode_ = value;
                onChanged();
                return this;
            }

            private double balanceAmt_;

            /**
             * <pre>
             * 账户余额
             * </pre>
             *
             * <code>optional double balanceAmt = 2;</code>
             */
            public boolean hasBalanceAmt() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 账户余额
             * </pre>
             *
             * <code>optional double balanceAmt = 2;</code>
             */
            public double getBalanceAmt() {
                return balanceAmt_;
            }

            /**
             * <pre>
             * 账户余额
             * </pre>
             *
             * <code>optional double balanceAmt = 2;</code>
             */
            public Builder setBalanceAmt(double value) {
                bitField0_ |= 0x00000002;
                balanceAmt_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 账户余额
             * </pre>
             *
             * <code>optional double balanceAmt = 2;</code>
             */
            public Builder clearBalanceAmt() {
                bitField0_ = (bitField0_ & ~0x00000002);
                balanceAmt_ = 0D;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:AccountCreateCmd)
        }

        // @@protoc_insertion_point(class_scope:AccountCreateCmd)
        private static final AccountCreateCmd DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new AccountCreateCmd();
        }

        public static AccountCreateCmd getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<AccountCreateCmd> PARSER = new com.google.protobuf.AbstractParser<AccountCreateCmd>() {
                                                                                    public AccountCreateCmd parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                         throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                        return new AccountCreateCmd(
                                                                                            input, extensionRegistry);
                                                                                    }
                                                                                };

        public static com.google.protobuf.Parser<AccountCreateCmd> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<AccountCreateCmd> getParserForType() {
            return PARSER;
        }

        public AccountCreateCmd getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface AccountCreateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountCreateEvent)
                                                com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        boolean hasAccountCode();

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        String getAccountCode();

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        com.google.protobuf.ByteString getAccountCodeBytes();

        /**
         * <pre>
         * 账户余额
         * </pre>
         *
         * <code>optional double balanceAmt = 2;</code>
         */
        boolean hasBalanceAmt();

        /**
         * <pre>
         * 账户余额
         * </pre>
         *
         * <code>optional double balanceAmt = 2;</code>
         */
        double getBalanceAmt();
    }

    /**
     * Protobuf type {@code AccountCreateEvent}
     */
    public static final class AccountCreateEvent extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AccountCreateEvent)
                                                                                               AccountCreateEventOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use AccountCreateEvent.newBuilder() to construct.
        private AccountCreateEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private AccountCreateEvent() {
            accountCode_ = "";
            balanceAmt_ = 0D;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private AccountCreateEvent(com.google.protobuf.CodedInputStream input,
                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            accountCode_ = bs;
                            break;
                        }
                        case 17: {
                            bitField0_ |= 0x00000002;
                            balanceAmt_ = input.readDouble();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return Account.internal_static_AccountCreateEvent_descriptor;
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return Account.internal_static_AccountCreateEvent_fieldAccessorTable.ensureFieldAccessorsInitialized(
                AccountCreateEvent.class, Builder.class);
        }

        private int                       bitField0_;
        public static final int           ACCOUNTCODE_FIELD_NUMBER = 1;
        private volatile Object accountCode_;

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        public boolean hasAccountCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        public String getAccountCode() {
            Object ref = accountCode_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    accountCode_ = s;
                }
                return s;
            }
        }

        /**
         * <pre>
         * 划拨账户
         * </pre>
         *
         * <code>optional string accountCode = 1;</code>
         */
        public com.google.protobuf.ByteString getAccountCodeBytes() {
            Object ref = accountCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                accountCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BALANCEAMT_FIELD_NUMBER = 2;
        private double          balanceAmt_;

        /**
         * <pre>
         * 账户余额
         * </pre>
         *
         * <code>optional double balanceAmt = 2;</code>
         */
        public boolean hasBalanceAmt() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 账户余额
         * </pre>
         *
         * <code>optional double balanceAmt = 2;</code>
         */
        public double getBalanceAmt() {
            return balanceAmt_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeDouble(2, balanceAmt_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(2, balanceAmt_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof AccountCreateEvent)) {
                return super.equals(obj);
            }
            AccountCreateEvent other = (AccountCreateEvent) obj;

            boolean result = true;
            result = result && (hasAccountCode() == other.hasAccountCode());
            if (hasAccountCode()) {
                result = result && getAccountCode().equals(other.getAccountCode());
            }
            result = result && (hasBalanceAmt() == other.hasBalanceAmt());
            if (hasBalanceAmt()) {
                result = result
                         && (Double.doubleToLongBits(getBalanceAmt()) == Double
                             .doubleToLongBits(other.getBalanceAmt()));
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasAccountCode()) {
                hash = (37 * hash) + ACCOUNTCODE_FIELD_NUMBER;
                hash = (53 * hash) + getAccountCode().hashCode();
            }
            if (hasBalanceAmt()) {
                hash = (37 * hash) + BALANCEAMT_FIELD_NUMBER;
                hash = (53 * hash)
                       + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getBalanceAmt()));
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static AccountCreateEvent parseFrom(java.nio.ByteBuffer data)
                                                                                    throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AccountCreateEvent parseFrom(java.nio.ByteBuffer data,
                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AccountCreateEvent parseFrom(com.google.protobuf.ByteString data)
                                                                                               throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AccountCreateEvent parseFrom(com.google.protobuf.ByteString data,
                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AccountCreateEvent parseFrom(byte[] data)
                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AccountCreateEvent parseFrom(byte[] data,
                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AccountCreateEvent parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static AccountCreateEvent parseFrom(java.io.InputStream input,
                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                       throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static AccountCreateEvent parseDelimitedFrom(java.io.InputStream input)
                                                                                              throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static AccountCreateEvent parseDelimitedFrom(java.io.InputStream input,
                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static AccountCreateEvent parseFrom(com.google.protobuf.CodedInputStream input)
                                                                                                      throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static AccountCreateEvent parseFrom(com.google.protobuf.CodedInputStream input,
                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                       throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(AccountCreateEvent prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code AccountCreateEvent}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
                                                                                                         implements
                                                                                                         // @@protoc_insertion_point(builder_implements:AccountCreateEvent)
                                                                                                         AccountCreateEventOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return Account.internal_static_AccountCreateEvent_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return Account.internal_static_AccountCreateEvent_fieldAccessorTable.ensureFieldAccessorsInitialized(
                    AccountCreateEvent.class, Builder.class);
            }

            // Construct using com.iquantex.phoenix.bankaccount.api.protobuf.Account.AccountCreateEvent.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                accountCode_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                balanceAmt_ = 0D;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return Account.internal_static_AccountCreateEvent_descriptor;
            }

            public AccountCreateEvent getDefaultInstanceForType() {
                return AccountCreateEvent.getDefaultInstance();
            }

            public AccountCreateEvent build() {
                AccountCreateEvent result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public AccountCreateEvent buildPartial() {
                AccountCreateEvent result = new AccountCreateEvent(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.accountCode_ = accountCode_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.balanceAmt_ = balanceAmt_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                            Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof AccountCreateEvent) {
                    return mergeFrom((AccountCreateEvent) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(AccountCreateEvent other) {
                if (other == AccountCreateEvent.getDefaultInstance())
                    return this;
                if (other.hasAccountCode()) {
                    bitField0_ |= 0x00000001;
                    accountCode_ = other.accountCode_;
                    onChanged();
                }
                if (other.hasBalanceAmt()) {
                    setBalanceAmt(other.getBalanceAmt());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                 throws java.io.IOException {
                AccountCreateEvent parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (AccountCreateEvent) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int              bitField0_;

            private Object accountCode_ = "";

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public boolean hasAccountCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public String getAccountCode() {
                Object ref = accountCode_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        accountCode_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public com.google.protobuf.ByteString getAccountCodeBytes() {
                Object ref = accountCode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((String) ref);
                    accountCode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public Builder setAccountCode(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                accountCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public Builder clearAccountCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                accountCode_ = getDefaultInstance().getAccountCode();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 划拨账户
             * </pre>
             *
             * <code>optional string accountCode = 1;</code>
             */
            public Builder setAccountCodeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                accountCode_ = value;
                onChanged();
                return this;
            }

            private double balanceAmt_;

            /**
             * <pre>
             * 账户余额
             * </pre>
             *
             * <code>optional double balanceAmt = 2;</code>
             */
            public boolean hasBalanceAmt() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 账户余额
             * </pre>
             *
             * <code>optional double balanceAmt = 2;</code>
             */
            public double getBalanceAmt() {
                return balanceAmt_;
            }

            /**
             * <pre>
             * 账户余额
             * </pre>
             *
             * <code>optional double balanceAmt = 2;</code>
             */
            public Builder setBalanceAmt(double value) {
                bitField0_ |= 0x00000002;
                balanceAmt_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 账户余额
             * </pre>
             *
             * <code>optional double balanceAmt = 2;</code>
             */
            public Builder clearBalanceAmt() {
                bitField0_ = (bitField0_ & ~0x00000002);
                balanceAmt_ = 0D;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:AccountCreateEvent)
        }

        // @@protoc_insertion_point(class_scope:AccountCreateEvent)
        private static final AccountCreateEvent DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new AccountCreateEvent();
        }

        public static AccountCreateEvent getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<AccountCreateEvent> PARSER = new com.google.protobuf.AbstractParser<AccountCreateEvent>() {
                                                                                      public AccountCreateEvent parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                                                                                                             throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                          return new AccountCreateEvent(
                                                                                              input, extensionRegistry);
                                                                                      }
                                                                                  };

        public static com.google.protobuf.Parser<AccountCreateEvent> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<AccountCreateEvent> getParserForType() {
            return PARSER;
        }

        public AccountCreateEvent getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_AccountCreateCmd_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_AccountCreateCmd_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor                internal_static_AccountCreateEvent_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_AccountCreateEvent_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        String[] descriptorData = { "\n src/main/proto/BankAccount.proto\";\n\020Ac"
                                              + "countCreateCmd\022\023\n\013accountCode\030\001 \001(\t\022\022\n\nb"
                                              + "alanceAmt\030\002 \001(\001\"=\n\022AccountCreateEvent\022\023\n"
                                              + "\013accountCode\030\001 \001(\t\022\022\n\nbalanceAmt\030\002 \001(\001B8"
                                              + "\n-com.iquantex.phoenix.bankaccount.api.p" + "rotobufB\007Account" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_AccountCreateCmd_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_AccountCreateCmd_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_AccountCreateCmd_descriptor, new String[] { "AccountCode", "BalanceAmt", });
        internal_static_AccountCreateEvent_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_AccountCreateEvent_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_AccountCreateEvent_descriptor, new String[] { "AccountCode", "BalanceAmt", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
