# app info config
spring:
  application:
    name: shopping-cart

# web config
server:
  port: 8080

# log config
logging.config: classpath:logback.xml

# 内存数据库管理页面
spring.h2:
  console:
    path: /h2-console
    enabled: true
    settings:
      web-allow-others: true

# phoenix
quantex:
  phoenix:
    routers:
      - message: com.iquantex.shopping.coreapi.hello.Hello$HelloCmd
        dst: shopping-cart/EA/Hello
      - message: com.iquantex.shoppingcart.coreapi.shopping.ShoppingCartOptionCmd
        dst: shopping-cart/EA/shoppingcart
      - message: com.iquantex.shoppingcart.coreapi.inventory.InventoryAllocateCmd
        dst: shopping-cart/EA/inventory
      - message: com.iquantex.shoppingcart.coreapi.shopping.ShoppingCartQueryListCmd
        dst: shopping-cart/EA/shoppingcart
      - message: com.iquantex.shoppingcart.coreapi.inventory.InventoryItemQueryCmd
        dst: shopping-cart/EA/inventory
    server:
      name: ${spring.application.name}
      mq:
        type: kafka
        address: embedded
      event-store:
        driver-class-name: org.h2.Driver
        snapshot:
          enabled: true
        data-sources:
          - url: jdbc:h2:file:./data/test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
            username: sa
            password:
    client:
      name: ${spring.application.name}-client
      mq:
        type: kafka
        address: embedded
