spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/turingdb;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL
#    url: jdbc:h2:mem:turingdb;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true

quantex:
  phoenix:
    server:
      event-store:
        driver-class-name: org.h2.Driver
        data-sources:
          - url: jdbc:h2:file:./db/eventstore;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL
#          - url: jdbc:h2:mem:eventstore;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL
            username: sa
            password:
