# app info config
spring:
  application:
    name: hello

# web config
server:
  port: 8080

# log config
logging.config: classpath:logback.xml

# 内存数据库管理页面
spring.h2:
  console:
    path: /h2-console
    enabled: true
    settings:
      web-allow-others: true

# Phoenix 配置
quantex:
  phoenix:
    client:
      name: ${spring.application.name}-client   # 服务名称
      mq:
        type: kafka                             # mq类型
        address: 127.0.0.1:9092                 # mq地址
    server:
      name: ${spring.application.name}    # 服务名称
      package-name: com.iquantex.samples.helloworld.domain   # 聚合根包所在路径
      default-serializer: proto_stuff # 默认序列化协议
      mq:
        type: kafka                       # mq类型
        address: 127.0.0.1:9092           # mq服务地址
        subscribe:
          - topic: ${spring.application.name}
      event-store:
        driver-class-name: org.h2.Driver
        data-sources:
          - url: jdbc:h2:~/data/test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
            username: sa
            password:                    # 数据库密码
