# app info config
spring:
  application:
    name: helloworld

# web config
server:
  port: 8080

# log config
logging.config: classpath:logback.xml

# 内存数据库管理页面
spring.h2:
  console:
    path: /h2-console
    enabled: true
    settings:
      web-allow-others: true

# phoenix
quantex:
  phoenix:
    routers:
      - message: com.iquantex.samples.helloworld.coreapi.Hello$HelloCmd
        dst: helloworld/EA/Hello
    server:
      name: ${spring.application.name}
      mq:
        type: kafka
        address: embedded
        subscribes:
          - topic: helloworld
      event-store:
        driver-class-name: org.h2.Driver
        data-sources:
          - url: jdbc:h2:file:./data/test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
            username: sa
            password:
    client:
      name: ${spring.application.name}-client
      mq:
        type: kafka
        address: embedded
