// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Phoenix.proto

package com.iquantex.phoenix.coreapi;

public final class Hello {

	private Hello() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface HelloCmdOrBuilder extends
			// @@protoc_insertion_point(interface_extends:HelloCmd)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		boolean hasHelloId();

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		java.lang.String getHelloId();

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		com.google.protobuf.ByteString getHelloIdBytes();

	}

	/**
	 * Protobuf type {@code HelloCmd}
	 */
	public static final class HelloCmd extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:HelloCmd)
			HelloCmdOrBuilder {

		private static final long serialVersionUID = 0L;

		// Use HelloCmd.newBuilder() to construct.
		private HelloCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private HelloCmd() {
			helloId_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private HelloCmd(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000001;
						helloId_ = bs;
						break;
					}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Hello.internal_static_HelloCmd_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return Hello.internal_static_HelloCmd_fieldAccessorTable
					.ensureFieldAccessorsInitialized(Hello.HelloCmd.class, Hello.HelloCmd.Builder.class);
		}

		private int bitField0_;

		public static final int HELLOID_FIELD_NUMBER = 1;

		private volatile java.lang.Object helloId_;

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		public boolean hasHelloId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		public java.lang.String getHelloId() {
			java.lang.Object ref = helloId_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			}
			else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					helloId_ = s;
				}
				return s;
			}
		}

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		public com.google.protobuf.ByteString getHelloIdBytes() {
			java.lang.Object ref = helloId_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				helloId_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, helloId_);
			}
			unknownFields.writeTo(output);
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, helloId_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Hello.HelloCmd)) {
				return super.equals(obj);
			}
			Hello.HelloCmd other = (Hello.HelloCmd) obj;

			boolean result = true;
			result = result && (hasHelloId() == other.hasHelloId());
			if (hasHelloId()) {
				result = result && getHelloId().equals(other.getHelloId());
			}
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (hasHelloId()) {
				hash = (37 * hash) + HELLOID_FIELD_NUMBER;
				hash = (53 * hash) + getHelloId().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Hello.HelloCmd parseFrom(java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Hello.HelloCmd parseFrom(java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Hello.HelloCmd parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Hello.HelloCmd parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Hello.HelloCmd parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Hello.HelloCmd parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Hello.HelloCmd parseFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static Hello.HelloCmd parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Hello.HelloCmd parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static Hello.HelloCmd parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static Hello.HelloCmd parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static Hello.HelloCmd parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Hello.HelloCmd prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code HelloCmd}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:HelloCmd)
				Hello.HelloCmdOrBuilder {

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return Hello.internal_static_HelloCmd_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return Hello.internal_static_HelloCmd_fieldAccessorTable
						.ensureFieldAccessorsInitialized(Hello.HelloCmd.class, Hello.HelloCmd.Builder.class);
			}

			// Construct using
			// com.iquantex.phoenix.bankaccount.coreapi.Hello.HelloCmd.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				helloId_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Hello.internal_static_HelloCmd_descriptor;
			}

			public Hello.HelloCmd getDefaultInstanceForType() {
				return Hello.HelloCmd.getDefaultInstance();
			}

			public Hello.HelloCmd build() {
				Hello.HelloCmd result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public Hello.HelloCmd buildPartial() {
				Hello.HelloCmd result = new Hello.HelloCmd(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.helloId_ = helloId_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Hello.HelloCmd) {
					return mergeFrom((Hello.HelloCmd) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Hello.HelloCmd other) {
				if (other == Hello.HelloCmd.getDefaultInstance())
					return this;
				if (other.hasHelloId()) {
					bitField0_ |= 0x00000001;
					helloId_ = other.helloId_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				Hello.HelloCmd parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Hello.HelloCmd) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object helloId_ = "";

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public boolean hasHelloId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public java.lang.String getHelloId() {
				java.lang.Object ref = helloId_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						helloId_ = s;
					}
					return s;
				}
				else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public com.google.protobuf.ByteString getHelloIdBytes() {
				java.lang.Object ref = helloId_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					helloId_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public Builder setHelloId(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				helloId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public Builder clearHelloId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				helloId_ = getDefaultInstance().getHelloId();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public Builder setHelloIdBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				helloId_ = value;
				onChanged();
				return this;
			}

			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:HelloCmd)

		}

		// @@protoc_insertion_point(class_scope:HelloCmd)
		private static final Hello.HelloCmd DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new Hello.HelloCmd();
		}

		public static Hello.HelloCmd getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		@java.lang.Deprecated
		public static final com.google.protobuf.Parser<HelloCmd> PARSER = new com.google.protobuf.AbstractParser<HelloCmd>() {
			public HelloCmd parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new HelloCmd(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<HelloCmd> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<HelloCmd> getParserForType() {
			return PARSER;
		}

		public Hello.HelloCmd getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface HelloEventOrBuilder extends
			// @@protoc_insertion_point(interface_extends:HelloEvent)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		boolean hasHelloId();

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		java.lang.String getHelloId();

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		com.google.protobuf.ByteString getHelloIdBytes();

	}

	/**
	 * Protobuf type {@code HelloEvent}
	 */
	public static final class HelloEvent extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:HelloEvent)
			HelloEventOrBuilder {

		private static final long serialVersionUID = 0L;

		// Use HelloEvent.newBuilder() to construct.
		private HelloEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private HelloEvent() {
			helloId_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private HelloEvent(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000001;
						helloId_ = bs;
						break;
					}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Hello.internal_static_HelloEvent_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return Hello.internal_static_HelloEvent_fieldAccessorTable
					.ensureFieldAccessorsInitialized(Hello.HelloEvent.class, Hello.HelloEvent.Builder.class);
		}

		private int bitField0_;

		public static final int HELLOID_FIELD_NUMBER = 1;

		private volatile java.lang.Object helloId_;

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		public boolean hasHelloId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		public java.lang.String getHelloId() {
			java.lang.Object ref = helloId_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			}
			else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					helloId_ = s;
				}
				return s;
			}
		}

		/**
		 * <pre>
		 * 聚合根ID
		 * </pre>
		 *
		 * <code>optional string helloId = 1;</code>
		 */
		public com.google.protobuf.ByteString getHelloIdBytes() {
			java.lang.Object ref = helloId_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				helloId_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, helloId_);
			}
			unknownFields.writeTo(output);
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, helloId_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Hello.HelloEvent)) {
				return super.equals(obj);
			}
			Hello.HelloEvent other = (Hello.HelloEvent) obj;

			boolean result = true;
			result = result && (hasHelloId() == other.hasHelloId());
			if (hasHelloId()) {
				result = result && getHelloId().equals(other.getHelloId());
			}
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (hasHelloId()) {
				hash = (37 * hash) + HELLOID_FIELD_NUMBER;
				hash = (53 * hash) + getHelloId().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Hello.HelloEvent parseFrom(java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Hello.HelloEvent parseFrom(java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Hello.HelloEvent parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Hello.HelloEvent parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Hello.HelloEvent parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Hello.HelloEvent parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Hello.HelloEvent parseFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static Hello.HelloEvent parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static Hello.HelloEvent parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static Hello.HelloEvent parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static Hello.HelloEvent parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static Hello.HelloEvent parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Hello.HelloEvent prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code HelloEvent}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:HelloEvent)
				Hello.HelloEventOrBuilder {

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return Hello.internal_static_HelloEvent_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return Hello.internal_static_HelloEvent_fieldAccessorTable
						.ensureFieldAccessorsInitialized(Hello.HelloEvent.class, Hello.HelloEvent.Builder.class);
			}

			// Construct using
			// com.iquantex.phoenix.bankaccount.coreapi.Hello.HelloEvent.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				helloId_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Hello.internal_static_HelloEvent_descriptor;
			}

			public Hello.HelloEvent getDefaultInstanceForType() {
				return Hello.HelloEvent.getDefaultInstance();
			}

			public Hello.HelloEvent build() {
				Hello.HelloEvent result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public Hello.HelloEvent buildPartial() {
				Hello.HelloEvent result = new Hello.HelloEvent(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.helloId_ = helloId_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Hello.HelloEvent) {
					return mergeFrom((Hello.HelloEvent) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Hello.HelloEvent other) {
				if (other == Hello.HelloEvent.getDefaultInstance())
					return this;
				if (other.hasHelloId()) {
					bitField0_ |= 0x00000001;
					helloId_ = other.helloId_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				Hello.HelloEvent parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Hello.HelloEvent) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object helloId_ = "";

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public boolean hasHelloId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public java.lang.String getHelloId() {
				java.lang.Object ref = helloId_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						helloId_ = s;
					}
					return s;
				}
				else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public com.google.protobuf.ByteString getHelloIdBytes() {
				java.lang.Object ref = helloId_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					helloId_ = b;
					return b;
				}
				else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public Builder setHelloId(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				helloId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public Builder clearHelloId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				helloId_ = getDefaultInstance().getHelloId();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * 聚合根ID
			 * </pre>
			 *
			 * <code>optional string helloId = 1;</code>
			 */
			public Builder setHelloIdBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				helloId_ = value;
				onChanged();
				return this;
			}

			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:HelloEvent)

		}

		// @@protoc_insertion_point(class_scope:HelloEvent)
		private static final Hello.HelloEvent DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new Hello.HelloEvent();
		}

		public static Hello.HelloEvent getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		@java.lang.Deprecated
		public static final com.google.protobuf.Parser<HelloEvent> PARSER = new com.google.protobuf.AbstractParser<HelloEvent>() {
			public HelloEvent parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new HelloEvent(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<HelloEvent> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<HelloEvent> getParserForType() {
			return PARSER;
		}

		public Hello.HelloEvent getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_HelloCmd_descriptor;

	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_HelloCmd_fieldAccessorTable;

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_HelloEvent_descriptor;

	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_HelloEvent_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\rPhoenix.proto\"\033\n\010HelloCmd\022\017\n\007helloId\030\001"
				+ " \001(\t\"\035\n\nHelloEvent\022\017\n\007helloId\030\001 \001(\tB*\n!c"
				+ "om.iquantex.phoenix.risk.coreapiB\005Hello" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_HelloCmd_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_HelloCmd_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_HelloCmd_descriptor, new java.lang.String[] { "HelloId", });
		internal_static_HelloEvent_descriptor = getDescriptor().getMessageTypes().get(1);
		internal_static_HelloEvent_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_HelloEvent_descriptor, new java.lang.String[] { "HelloId", });
	}

	// @@protoc_insertion_point(outer_class_scope)

}
