#!/bin/sh
# 发布coreapi到maven私有仓库
set -e

if [ $# -ne 1 ]
then
  echo "$0 version"
  exit 0
fi

# 回到工程目录
cd `dirname $0`/../
pwd

version=$1
mvn versions:set -DoldVersion='*' -DnewVersion=${version}
mvn clean deploy -pl coreapi -am
mvn versions:revert
